/* ============================================================================
 * POLECAT GAME CATALOG
 * ----------------------------------------------------------------------------
 * Single source of truth for every game on games.polecat.live.
 * The home page renders from this list; the hourly build-loop flips entries
 * from status:"soon" -> "live" as games ship, and may add screenshots/genres.
 *
 * Each entry:
 *   id      unique slug (also the folder under /games/<id>/)
 *   title   the game's name (not just the property)
 *   source  the public-domain property it draws from
 *   genre   gameplay category (drives variety + the genre filter)
 *   style   visual style: "8-bit" | "16-bit" (future: "3d","vector","mono")
 *   gen     console-history generation: 3 = 8-bit/NES (default), 4 = 16-bit/SNES,
 *           5 = 32/64-bit 3D (future). Gen 1/2 (Odyssey/Atari) reserved for any
 *           deliberately primitive throwbacks. Drives the "GEN n" card badge.
 *   property (optional) groups a property's generations into ONE home card with
 *           an 8-bit/16-bit play switch. Every property should eventually have
 *           BOTH a Gen-3 (8-bit) and a Gen-4 (16-bit) entry sharing this key.
 *   accent  hex color used for the procedural thumbnail
 *   blurb   one-line pitch shown on the card
 *   status  "live" (playable) | "soon" (planned)
 *   tags    extra filter keywords
 * ============================================================================ */
window.POLECAT_CATALOG = [
  // ---------------------------- LIVE (built) ----------------------------
  { id: "sherlock-16", title: "Sherlock Holmes", source: "The Hound of the Baskervilles — A. C. Doyle", genre: "Mystery", style: "16-bit", gen: 4, property: "Sherlock Holmes", accent: "#5dff8f", status: "live",
    blurb: "THE HOUND OF THE BASKERVILLES — the 16-bit mystery. Work a pinned case map of Dartmoor: each lead a run of phases ending in a confrontation — the spy's cab, the candle at the window, the convict on the tor, the hound in the fog — with the lens, revolver, notebook and portrait carried between leads and a branching final chapter.", tags: ["detective","multi-chapter","mystery","16-bit","hub"] },
  { id: "sherlock-hound", title: "The Hound of the Baskervilles", source: "Sherlock Holmes — A. Conan Doyle", genre: "Mystery", style: "8-bit", gen: 3, property: "Sherlock Holmes", accent: "#5dff8f", status: "live",
    blurb: "Five chapters of detection — deduce the cane, cross the Grimpen Mire, search the foggy moor, piece the warning, and face the Hound.", tags: ["detective","multi-chapter","mystery"] },
  { id: "dracula-castle", title: "Dracula", source: "Dracula — Bram Stoker", genre: "Horror", style: "16-bit", gen: 4, property: "Dracula", accent: "#c8102e", status: "live",
    blurb: "NIGHTS OF BLOOD — the 16-bit chronicle. Cross a hub map of the novel: each night a run of escalating trials and a mini-boss, relics that carry between them, a branching escape, and the Count hunted to dust before sunrise.", tags: ["horror","multi-chapter","vampire","16-bit","hub"] },
  { id: "dracula-8bit", title: "Dracula", source: "Dracula — Bram Stoker", genre: "Horror", style: "8-bit", gen: 3, property: "Dracula", accent: "#c8102e", status: "live",
    blurb: "The 8-bit original — five chapters through Stoker's novel: the castle wall, the doomed Demeter, Renfield's flies, Lucy's tomb, and the final reckoning at sunset.", tags: ["horror","multi-chapter","vampire"] },
  // ----------- LEGACY single-mechanic games (hidden from the home grid &
  // search via legacy:true until they're rebuilt in the multi-chapter story
  // mode). Still playable by direct URL; drop the flag once upgraded. -----------
  { id: "alice-rabbithole", title: "Alice in Wonderland", source: "Alice in Wonderland — Lewis Carroll", genre: "Story Arcade", style: "8-bit", accent: "#21e6ff", status: "live",
    blurb: "Five Wonderland tales — tumble down the rabbit hole, swim the pool of tears, time the Mad Hatter's cups, swing a flamingo at the Queen's croquet, and dodge flying cards at the trial!", tags: ["arcade","adventure","multi-chapter"] },
  { id: "oz-yellowbrick", title: "The Wizard of Oz", source: "The Wizard of Oz — L. Frank Baum", genre: "Story Arcade", style: "8-bit", accent: "#ffe14d", status: "live",
    blurb: "Five Oz tales — survive the twister, run the yellow brick road, wake friends in the poppy field, dodge the Wizard's fire, and click ruby heels to get home.", tags: ["arcade","adventure","multi-chapter"] },
  { id: "frankenstein-spark", title: "Frankenstein", source: "Frankenstein — Mary Shelley", genre: "Horror Adventure", style: "8-bit", accent: "#5dff8f", status: "live",
    blurb: "Five gothic chapters: channel lightning to birth the Creature, flee the frightened village, spy on the De Laceys, chase across Arctic ice, and make the final leap into darkness.", tags: ["horror","multi-chapter","gothic"] },

  // ---------------------------- SOON (planned) ----------------------------
  { id: "pooh-hunny", title: "Hunny Hunt", source: "Winnie-the-Pooh — A. A. Milne (1926)", genre: "Puzzle Collect", style: "8-bit", accent: "#ffe14d", status: "live",
    blurb: "Float by balloon to the bees' hive, follow the Woozle tracks, gather gifts for Eeyore's party, steer Piglet through the Blustery Day, and wiggle Pooh free from Rabbit's door.", tags: ["cozy","puzzle","multi-chapter"] },
  { id: "mickey-steamboat", title: "Steamboat Willie", source: "Mickey Mouse (1928 — Steamboat Willie)", genre: "Rhythm Action", style: "8-bit", accent: "#e8c050", status: "live",
    blurb: "Steer the steamboat past river debris, tap the whistle in time, play the animal band, catch Minnie's parcels, and dodge Captain Pete's furious swings to escape!", tags: ["rhythm","action","multi-chapter"] },
  { id: "robinhood-16", title: "Robin Hood", source: "Robin Hood — Howard Pyle", genre: "Action Adventure", style: "16-bit", gen: 4, property: "Robin Hood", accent: "#5dff8f", status: "live",
    blurb: "THE OUTLAW OF SHERWOOD — the 16-bit legend. Roam a Sherwood hub map, play every tale in any order: the golden-arrow tournament, the forest ride, the log-bridge duel with Little John, the Bishop's feast and gallows rescue, and the Sheriff's keep — with gear that carries between them and a branching ending.", tags: ["action-adventure","multi-chapter","archery","16-bit","hub"] },
  { id: "robinhood-archer", title: "Sherwood Sharpshooter", source: "Robin Hood — English folklore", genre: "Aim / Archery", style: "8-bit", gen: 3, property: "Robin Hood", accent: "#5dff8f", status: "live",
    blurb: "Split the shaft at the tournament, ride through Sherwood, duel Little John, rob the rich, and face the Sheriff to free Maid Marian.", tags: ["aim","skill","multi-chapter"] },
  { id: "arthur-16", title: "King Arthur", source: "King Arthur — Arthurian legend", genre: "Action Adventure", style: "16-bit", gen: 4, property: "King Arthur", accent: "#21e6ff", status: "live",
    blurb: "THE ONCE AND FUTURE KING — the 16-bit legend. Take any seat at the Round Table: heave the sword from the stone, keep the skiff in the Lady's calm, shatter lances in the joust, duel Lancelot at the ford, pass the Chapel Perilous, and hold the dragon standard at Camlann before the last duel with Mordred — with Excalibur, the oath and the Grail's grace carried between quests, and a coronation choice that writes the ending.", tags: ["adventure","quest","myth","multi-chapter","16-bit","hub"] },
  { id: "arthur-sword", title: "The Sword in the Stone", source: "King Arthur — Arthurian legend", genre: "Action Adventure", style: "8-bit", gen: 3, property: "King Arthur", accent: "#21e6ff", status: "live",
    blurb: "Pull Excalibur from the stone, joust at the tournament, defend Camelot's gates, and seek the Holy Grail across five chapters.", tags: ["adventure","quest","multi-chapter"] },
  { id: "peterpan-flight", title: "Second Star to the Right", source: "Peter Pan — J. M. Barrie", genre: "Flight Dodge", style: "8-bit", accent: "#ffe14d", status: "live",
    blurb: "Five Neverland tales — fly over London rooftops, rescue Tiger Lily, run from Tick-Tock the croc, defend the Lost Boys' hideout, and duel Captain Hook on the Jolly Roger.", tags: ["flight","dodge","multi-chapter"] },
  { id: "cinderella-ball", title: "Before Midnight", source: "Cinderella — Perrault / Grimm", genre: "Time Attack", style: "8-bit", accent: "#ff2e97", status: "live",
    blurb: "Finish the chores, catch the Fairy Godmother's sparkles, waltz with the Prince, race the midnight clock, and guide the glass slipper home.", tags: ["time","arcade","multi-chapter"] },
  { id: "snowwhite-apple", title: "Seven for the Mine", source: "Snow White — Brothers Grimm", genre: "Mining Puzzle", style: "8-bit", accent: "#5dff8f", status: "live",
    blurb: "Find Snow White in the magic mirror, flee the enchanted forest, catch gems in the dwarfs' mine, dodge the Evil Queen's poisoned apples, and fill the heart with true love's kiss.", tags: ["fairy-tale","puzzle","multi-chapter"] },
  { id: "tarzan-vines", title: "Lord of the Vines", source: "Tarzan of the Apes — E. R. Burroughs", genre: "Swing Platformer", style: "8-bit", accent: "#5dff8f", status: "live",
    blurb: "Dodge the jungle cradle dangers, swing the canopy vine by vine, duel mighty Kerchak, slip past ape patrols to rescue Jane, and drive ivory hunters from Tarzan's domain.", tags: ["swing","action","multi-chapter"] },
  { id: "pinocchio-nose", title: "No Strings", source: "Pinocchio — Carlo Collodi", genre: "Story Arcade", style: "8-bit", accent: "#4ab8e8", status: "live",
    blurb: "Five scenes from Collodi's tale — wish the puppet to life, dodge bandits on the road, escape Stromboli's cage, flee Pleasure Island before you're turned into a donkey, and light a fire inside Monstro.", tags: ["arcade","adventure","multi-chapter"] },
  { id: "hercules-labors", title: "The Twelve Labors", source: "Hercules — Greek mythology", genre: "Boss Rush", style: "8-bit", accent: "#CD7F32", status: "live",
    blurb: "Strike the Nemean Lion, sever the Hydra's heads, dodge Stymphalian feathers, steer the river through the Augean Stables, and face three-headed Cerberus at the gates of Hades.", tags: ["boss","action","multi-chapter"] },
  { id: "thor-loki", title: "Hammer of the Gods", source: "Thor & Loki — Norse mythology", genre: "Brawler", style: "8-bit", accent: "#e8c84a", status: "live",
    blurb: "Cross the rainbow bridge, haul the World Serpent, catch shape-shifting Loki, hold three Asgard gates against Fenrir's wolves, and face fire-giant Surtr at Ragnarök.", tags: ["brawler","action","multi-chapter"] },
  { id: "pride-prejudice", title: "A Matter of Pride", source: "Pride and Prejudice — Jane Austen", genre: "Dialogue Strategy", style: "8-bit", accent: "#c85a7a", status: "live",
    blurb: "A Regency dating-sim in four scenes — trade branching banter with Darcy at the Meryton Assembly, step the minuet in time with his lead, complete his letter as a word puzzle, and answer his second proposal at Pemberley. AFFECTION and REPUTATION meters carry through to the ending.", tags: ["romance","dialogue","dating-sim","multi-chapter"] },
  { id: "gatsby-green", title: "The Green Light", source: "The Great Gatsby — F. Scott Fitzgerald", genre: "Rhythm Party", style: "8-bit", accent: "#d4a017", status: "live",
    blurb: "Catch the jazz at Gatsby's party, race the yellow roadster to Manhattan, reach across the bay for Daisy's green dock light, hold your ground at the Plaza Hotel, and outrun the shadows in the Valley of Ashes.", tags: ["rhythm","jazz","multi-chapter"] },
  { id: "scrooge-carol", title: "Scrooge's Long Night", source: "A Christmas Carol — Charles Dickens", genre: "Narrative Maze", style: "8-bit", accent: "#d4a020", status: "live",
    blurb: "Dodge Marley's chains, gather glowing memories with the Ghost of Christmas Past, catch the Cratchit feast, evade the Shadow's pointing finger, then race through London on Christmas morning.", tags: ["story","multi-chapter","dickens"] },
  { id: "musketeers-duel", title: "All for One", source: "The Three Musketeers — Alexandre Dumas", genre: "Fencing Duel", style: "8-bit", accent: "#c8961e", status: "live",
    blurb: "Ride to Paris, duel the Musketeers at dawn, steal back the Queen's diamonds, hold the siege of La Rochelle, and face the Cardinal's champion in a final clash of steel.", tags: ["duel","action","multi-chapter"] },
  { id: "montecristo-escape", title: "The Count's Revenge", source: "The Count of Monte Cristo — Alexandre Dumas", genre: "Escape & Revenge", style: "8-bit", accent: "#e3c567", status: "live",
    blurb: "Five acts through Dumas' epic — dodge the betrayal, chip through Château d'If, seize the island treasure, swim to freedom, and expose three conspirators to justice.", tags: ["escape","adventure","multi-chapter"] },
  { id: "mobydick-hunt", title: "The White Whale", source: "Moby-Dick — Herman Melville", genre: "Harpoon Action", style: "8-bit", accent: "#21e6ff", status: "live",
    blurb: "Sign on at Nantucket, lower the longboat for the first strike, survive the great squid, trim the sails through a typhoon, and chase the White Whale across three days to the bitter end.", tags: ["action","sea","multi-chapter"] },
  { id: "phantom-opera", title: "Beneath the Opera", source: "The Phantom of the Opera — G. Leroux", genre: "Stealth Pursuit", style: "8-bit", accent: "#cc2233", status: "live",
    blurb: "Slip through the torch-lit catacombs, sing Erik's aria across a real five-line staff, shield Christine on the rooftop, drop the great chandelier, and row silent past the mob's lanterns to freedom.", tags: ["stealth","horror","multi-chapter","rhythm"] },
  { id: "phantom-1925", title: "The Masque", source: "Phantom of the Opera (1925 film)", genre: "Chase Horror", style: "8-bit", accent: "#D82800", status: "live",
    blurb: "Five scenes from Rupert Julian's 1925 silent film: stalk the masquerade as the Red Death, entrance Christine at the organ, drop the chandelier, steer the gondola through torch-lit catacombs, and flee the Paris mob.", tags: ["chase","horror","multi-chapter","silent-film"] },
  { id: "zorro-mark", title: "The Mark of Zorro", source: "Zorro — The Curse of Capistrano", genre: "Swashbuckler", style: "8-bit", accent: "#c8102e", status: "live",
    blurb: "Carve your Z on three walls, ride Tornado through the dark canyon, duel the Commandante, free the peons, and face the Alcalde in a final clash of blades.", tags: ["swashbuckler","action","multi-chapter"] },
  { id: "timemachine-eloi", title: "802,701 A.D.", source: "The Time Machine — H. G. Wells", genre: "Survival Strategy", style: "8-bit", accent: "#44ff88", status: "live",
    blurb: "Five eras from Wells' classic — calibrate the time circuits, gather fruit in the Eloi's far-future garden, sneak past Morlock sentries, navigate tunnels by matchlight, and dodge temporal debris racing back to 1895.", tags: ["survival","scifi","multi-chapter"] },
  { id: "warworlds-16", title: "The War of the Worlds", source: "The War of the Worlds — H. G. Wells", genre: "Survival Shooter", style: "16-bit", gen: 4, property: "The War of the Worlds", accent: "#44ee44", status: "live",
    blurb: "THE COMING OF THE MARTIANS — the 16-bit invasion. Answer dispatches on a phosphor war-map: watch the pit at Horsell (and don't get caught watching), flee the sweeping heat-ray, lay artillery arcs at Weybridge, out-wait the searching tentacle, ride the exodus past the Thunder Child's last stand, and creep cover-to-cover through dead London — one wire home changes the ending.", tags: ["shooter","survival","sci-fi","multi-chapter","16-bit","hub"] },
  { id: "warworlds-tripods", title: "Tripods", source: "The War of the Worlds — H. G. Wells", genre: "Survival Shooter", style: "8-bit", gen: 3, property: "The War of the Worlds", accent: "#44ee44", status: "live",
    blurb: "Dodge the heat-ray on Horsell Common, flee burning London, man the guns of the Thunder Child, slip through the black smoke, and guide the last survivors past the falling tripods.", tags: ["shooter","survival","multi-chapter"] },
  { id: "jekyll-hyde", title: "Two Minds", source: "Dr. Jekyll and Mr. Hyde — R. L. Stevenson", genre: "Transformation Puzzle", style: "8-bit", accent: "#9b5cff", status: "live",
    blurb: "Brew the transformation formula, prowl London as Hyde, silence the witnesses, hoard the last vials, and hold the locked door against the beast within.", tags: ["puzzle","horror","multi-chapter"] },
  { id: "nemo-nautilus", title: "20,000 Leagues", source: "Captain Nemo — Jules Verne", genre: "Submarine Shmup", style: "8-bit", accent: "#00c8a0", status: "live",
    blurb: "Hunt the sea monster aboard the Abraham Lincoln, dive the coral kingdom in a walking suit, survive the giant squid, ram through polar ice, and escape the Norway Maelstrom.", tags: ["shmup","sea","multi-chapter"] },
  { id: "cthulhu-call", title: "The Call", source: "The Call of Cthulhu — H. P. Lovecraft", genre: "Sanity Survival", style: "8-bit", accent: "#00cc55", status: "live",
    blurb: "Five accounts of cosmic dread — decode Cthulhu's idol glyphs, weave through the bayou cult's torchlight, steer the yacht to R'lyeh, gather runes in the impossible city, and ram the Great Old One before your sanity breaks.", tags: ["horror","sanity","multi-chapter","lovecraft"] },
  { id: "kingkong-climb", title: "Eighth Wonder", source: "King Kong (1932 novelization)", genre: "Climb Defense", style: "8-bit", accent: "#ff8a3d", status: "live",
    blurb: "Five scenes from the 1933 legend — survive Skull Island, dodge prehistoric jaws on the great log, break free from Broadway chains, rampage through New York, and swat biplanes from atop the Empire State Building.", tags: ["climb","action","multi-chapter"] },
  { id: "notld-survive", title: "They're Coming", source: "Night of the Living Dead (1968)", genre: "Tower Defense", style: "8-bit", accent: "#cc1122", status: "live",
    blurb: "Five nights from Romero's 1968 masterpiece — flee the cemetery, board the farmhouse windows, gather supplies in the dark, hold three breach points against the growing horde, and race to the dawn.", tags: ["defense","horror","multi-chapter"] },
  { id: "littlemermaid-sea", title: "The Sea King's Daughter", source: "The Little Mermaid — H. C. Andersen", genre: "Swim Collect", style: "8-bit", accent: "#00d4b8", status: "live",
    blurb: "Swim to the surface on your 15th birthday, navigate the sea witch's tentacled cave, rescue the drowning prince, dance at the palace, and catch the sea spirits' gifts at dawn.", tags: ["swim","story","multi-chapter"] },
  { id: "tomsawyer-fence", title: "Whitewash & Wonder", source: "Tom Sawyer — Mark Twain", genre: "Adventure Arcade", style: "8-bit", accent: "#c87a10", status: "live",
    blurb: "Trick kids into whitewashing the fence, dodge Injun Joe's lantern at midnight, raft down the Mississippi, escape McDougal's Cave, and dig up the buried treasure.", tags: ["adventure","arcade","multi-chapter"] },
  { id: "huckfinn-raft", title: "Down the Mississippi", source: "Huckleberry Finn — Mark Twain", genre: "Journey Sim", style: "8-bit", accent: "#f0c020", status: "live",
    blurb: "An Oregon-Trail-style river journey — fish for supplies, bluff through raftsmen encounters that spend your GRUB & TRUST economy, navigate Cairo fog by starlight, sort evidence to expose the King's fraud, and throw a rope to free Jim from the Phelps farm.", tags: ["sim","strategy","multi-chapter","adventure"] },
  { id: "lesmis-escape", title: "24601", source: "Les Misérables — Victor Hugo", genre: "Drama", style: "8-bit", accent: "#cc2233", status: "live",
    blurb: "Five acts of Hugo's epic — row the Toulon galleys, steal bread on winter streets, gather water for Cosette, defend the June barricades, then carry Marius through the dark Paris sewers.", tags: ["stealth","drama","multi-chapter"] },
  { id: "doriangray-portrait", title: "The Portrait", source: "The Picture of Dorian Gray — O. Wilde", genre: "Decay Puzzle", style: "8-bit", accent: "#cc9830", status: "live",
    blurb: "Five Victorian chapters — dodge Lord Henry's platitudes in the studio, catch roses at the Lyceum, sort the yellow book's poisoned pages, hide from James Vane in the East End fog, and strike the corrupted portrait in the locked room.", tags: ["puzzle","horror","multi-chapter","gothic"] },
  { id: "grimm-tales", title: "Grimm's Path", source: "Grimm's Fairy Tales", genre: "Story Arcade", style: "8-bit", accent: "#d4a020", status: "live",
    blurb: "Five dark fairy tales from Jacob & Wilhelm Grimm — dodge the wolf through the forest, climb Rapunzel's tower, push the witch into her own oven, spin straw into gold, and wake the sleeping princess with true love's kiss.", tags: ["fairy-tale","story","multi-chapter"] },
  { id: "1001nights-magic", title: "A Thousand Nights", source: "One Thousand and One Nights", genre: "Adventure", style: "8-bit", accent: "#e8b020", status: "live",
    blurb: "Five tales from One Thousand and One Nights — spin Scheherazade's tale for the Sultan, steer Sinbad through the Roc's shadow, grab Ali Baba's treasure, command Aladdin's Genie, and race the flying carpet to the palace.", tags: ["adventure","magic","multi-chapter"] },
  { id: "odyssey-16", title: "The Odyssey", source: "The Odyssey — Homer", genre: "Voyage Adventure", style: "16-bit", gen: 4, property: "The Odyssey", accent: "#4ac8d4", status: "live",
    blurb: "THE LONG WAY HOME — the 16-bit epic. Sail an open chart of the wine-dark sea: drive the stake and flee the Cyclops' boulders (taunt him for extra glory, if you dare), guard the bag of winds, out-charm Circe, row the Sirens' strait past Scylla, and string the great bow — with wine, winds, moly and a loyal crew carried between islands and a shout that changes the ending.", tags: ["adventure","sea","myth","multi-chapter","16-bit","hub"] },
  { id: "odysseus-voyage", title: "The Long Way Home", source: "Odysseus — The Odyssey", genre: "Voyage Adventure", style: "8-bit", gen: 3, property: "The Odyssey", accent: "#4ac8d4", status: "live",
    blurb: "Five crossings on the wine-dark sea — escape the Cyclops' cave, collect moly on Circe's island, resist the Sirens, steer between Scylla and Charybdis, and string the great bow at Ithaca.", tags: ["adventure","sea","multi-chapter"] },
  { id: "odyssey-sirens", title: "Song of the Sirens", source: "The Odyssey — Homer", genre: "Rhythm Dodge", style: "8-bit", accent: "#F8B800", status: "live",
    blurb: "Five crossings from Homer's Odyssey — balance the storm-tossed ship, summon the right shades, resist the Sirens' golden song, dodge Scylla's snapping heads, and steer a desperate raft through Poseidon's fury.", tags: ["rhythm","myth","multi-chapter","adventure"] },
  { id: "iliad-troy", title: "Wrath of Achilles", source: "The Iliad — Homer", genre: "Battle Tactics", style: "8-bit", accent: "#c87a20", status: "live",
    blurb: "Five books of Homer's epic — muster the fleet, advance across the Trojan plain, hold the phalanx at the gates, shield Patroclus from Apollo's arrows, and chase Hector to his fate.", tags: ["tactics","action","multi-chapter"] },
  { id: "beowulf-grendel", title: "Beowulf", source: "Beowulf — Old English epic", genre: "Boss Brawler", style: "8-bit", accent: "#c8962a", status: "live",
    blurb: "Five deeds from the Old English epic — sail the whale-road, wrestle Grendel, dive the blood-dark mere, face the fire drake, and hold the final shield wall.", tags: ["boss","brawler","multi-chapter"] },
  { id: "hunchback-bells", title: "The Bells of Notre-Dame", source: "The Hunchback of Notre-Dame — Hugo", genre: "Climb Rescue", style: "8-bit", accent: "#9b5cff", status: "live",
    blurb: "Swing the great bells and scale the cathedral to claim sanctuary.", tags: ["climb","story"] },
  { id: "nosferatu-1922", title: "Shadow of the Vampyr", source: "Nosferatu (1922 film)", genre: "Stealth Horror", style: "8-bit", accent: "#cc1122", status: "live",
    blurb: "Five nights from Murnau's 1922 masterpiece — steer Hutter's carriage past wolves, explore Orlok's castle for journal pages, seal coffins on the plague ship Demeter, guide the shadow up the staircase, and hold the vampire at bay until dawn.", tags: ["horror","stealth","multi-chapter"] },
  { id: "metropolis-1927", title: "Heart Machine", source: "Metropolis (1927 film)", genre: "Industrial Platformer", style: "8-bit", accent: "#40d0ff", status: "live",
    blurb: "Five chapters through Fritz Lang's masterpiece — stabilise the pressure dial, fall the workers' shaft, guide Maria's children from the flood, expose Rotwang's robot at the revel, and climb the cathedral to ring the great bell.", tags: ["platform","scifi","multi-chapter"] },
  { id: "mulan-ballad", title: "Ballad of Honor", source: "Hua Mulan — Ballad of Mulan", genre: "Action RPG", style: "8-bit", accent: "#cc2200", status: "live",
    blurb: "Five chapters of Hua Mulan's legend — don the soldier's disguise, survive arrow trials at the training camp, fire the mountain cannon at Shan-Yu's army, slip through the imperial palace past torchlit guards, and duel the warlord blade-to-blade on the rooftop.", tags: ["action","rpg","multi-chapter","warrior"] },
  { id: "scrooge-ledger", title: "Bah, Humbug!", source: "A Christmas Carol — Charles Dickens", genre: "Story Arcade", style: "8-bit", accent: "#D4A020", status: "live",
    blurb: "Five chapters from Dickens' carol — count shillings in the cold countinghouse, dodge Marley's chains, relive Christmas Past by candlelight, deliver the Spirit's gifts, and escape the pointing Ghost of Christmas Yet to Come.", tags: ["story","arcade","multi-chapter","dickens"] },
  { id: "tripmoon-1902", title: "A Trip to the Moon", source: "A Trip to the Moon (1902 film)", genre: "Cannon Launch", style: "8-bit", accent: "#c88020", status: "live",
    blurb: "Five chapters through Méliès' masterpiece — vote for the expedition, load the great cannon, steer through star-dancers in space, battle Selenites on the Moon, and guide the capsule home to the Pacific.", tags: ["launch","arcade","multi-chapter","film"] },
  { id: "sleepyhollow-ride", title: "The Headless Horseman", source: "The Legend of Sleepy Hollow — Irving", genre: "Night Chase", style: "8-bit", accent: "#ff8a3d", status: "live",
    blurb: "Collect lanterns in the haunted hollow, teach Sleepy Hollow's school, feast at Van Tassel's harvest party, ride for your life at midnight, and reach the covered bridge before the Horseman catches you.", tags: ["chase","horror","multi-chapter"] },
  { id: "invisibleman-fade", title: "Unseen", source: "The Invisible Man — H. G. Wells", genre: "Stealth Puzzle", style: "8-bit", accent: "#21e6ff", status: "live",
    blurb: "Three encounters from Wells' 1897 classic — brew the invisibility compound, then run one unbroken manhunt from the suspicious village through the betraying snow to the torch-lit commons on a persistent exposure meter, before defending Kemp's house from soldiers.", tags: ["stealth","puzzle","multi-chapter"] },
  { id: "journeycenter-earth", title: "To the Center", source: "Journey to the Center of the Earth — Verne", genre: "Descent Resource Sim", style: "8-bit", accent: "#c87a20", status: "live",
    blurb: "A Verne descent resource-sim: ration AIR, ROPE, and LIGHT before you enter. Navigate granite tunnels, catch oxygen bubbles on Lidenbrock Sea, match prehistoric fossils by torchlight, and operate the eruption valves to escape.", tags: ["sim","strategy","puzzle","multi-chapter"] },
  { id: "around80days-race", title: "Around the World", source: "Around the World in Eighty Days — Verne", genre: "Race Manager", style: "8-bit", accent: "#d4a017", status: "live",
    blurb: "Five legs of Fogg's wager — seal the bet at the Reform Club, steer the Mongolia to Suez, ride an elephant across India, stoke the Henrietta's boiler, and race a carriage through night London.", tags: ["race","adventure","multi-chapter"] },
  { id: "treasureisland-map", title: "X Marks the Spot", source: "Treasure Island — R. L. Stevenson", genre: "Treasure Hunt", style: "8-bit", accent: "#ffe14d", status: "live",
    blurb: "Find the map at the inn, sail the Hispaniola through treacherous seas, hold the stockade, slip through the jungle, and dig for Flint's buried hoard.", tags: ["adventure","pirate","multi-chapter"] },
  { id: "junglebook-mowgli", title: "The Jungle Book", source: "The Jungle Book — Rudyard Kipling", genre: "Action Adventure", style: "8-bit", accent: "#5dff8f", status: "live",
    blurb: "Five tales from Kipling's classic — run with the wolf pack, learn the Master Words from Baloo, hypnotize the Bandar-log, steal fire from the man-village, and face Shere Khan in the torchlight.", tags: ["action","adventure","multi-chapter"] },
  { id: "donquixote-tilt", title: "Tilting at Windmills", source: "Don Quixote — Cervantes", genre: "Joust Arcade", style: "8-bit", accent: "#e0b040", status: "live",
    blurb: "Five adventures through Cervantes' classic: thread your lance through rotating windmill arms, stab wineskin 'monsters' at the inn, dodge rocks from freed galley slaves, navigate the Cave of Montesinos by torchlight, and face the Knight of the White Moon in a final joust.", tags: ["arcade","adventure","multi-chapter"] },
  { id: "annegreen-gables", title: "Anne of Green Gables", source: "Anne of Green Gables — L. M. Montgomery", genre: "Story Arcade", style: "8-bit", accent: "#d44878", status: "live",
    blurb: "Five tales from Montgomery's 1908 classic — ride Matthew's buggy past the White Way of Delight, bake without the liniment, survive the great hair-dye disaster, brave the Haunted Wood, and win the Avery Scholarship.", tags: ["story","arcade","multi-chapter","cozy"] },
  { id: "littlewomen-march", title: "Little Women", source: "Little Women — Louisa May Alcott", genre: "Story Arcade", style: "8-bit", accent: "#c84868", status: "live",
    blurb: "Five chapters from Alcott's 1868 classic — catch Christmas gifts for the Hummels, perform Jo's Pickwick melodrama, dodge cracks on Amy's frozen pond, tend Beth through the long fever nights, and welcome Father home from the war.", tags: ["story","arcade","multi-chapter"] },
  { id: "secretgarden-bloom", title: "The Secret Garden", source: "The Secret Garden — F. H. Burnett", genre: "Garden Puzzle", style: "8-bit", accent: "#e84090", status: "live",
    blurb: "Follow the robin to the hidden door, plant seeds in the winter garden, calm Dickon's wild creatures, give Colin courage to walk, and gather the garden's magic across five enchanted chapters.", tags: ["puzzle","cozy","multi-chapter"] },
  { id: "whitefang-wild", title: "White Fang", source: "White Fang — Jack London", genre: "Survival Sim", style: "8-bit", accent: "#7ac8ff", status: "live",
    blurb: "Five Yukon chapters — dodge eagle strikes as a lone wolf cub, collect fish under the sled dogs' cruelty, counter-attack in Beauty Smith's fight ring, earn Weedon Scott's trust through patient timing, and chase Jim Hall through the dark house to protect the sleeping judge.", tags: ["survival","action","multi-chapter"] },
  { id: "callwild-buck", title: "The Call of the Wild", source: "The Call of the Wild — Jack London", genre: "Sled Runner", style: "8-bit", accent: "#4ab8e8", status: "live",
    blurb: "Five stretches of Buck's Yukon journey — dodge the rope in the California night, steer the sled team through the snow, duel lead dog Spitz on the ice, pull Thornton's impossible wager, and answer the howl of the wild.", tags: ["runner","adventure","multi-chapter"] },
  { id: "olivertwist-dodge", title: "Please, Sir", source: "Oliver Twist — Charles Dickens", genre: "Pickpocket Stealth", style: "8-bit", accent: "#c88820", status: "live",
    blurb: "Five acts of Dickensian survival — dodge the beadle's cane, pick Fagin's pocket, silence lying witnesses, creep past lantern guards, and flee Bill Sikes on the London rooftops.", tags: ["stealth","arcade","multi-chapter","dickens"] },
  { id: "greatexpect-pip", title: "Great Expectations", source: "Great Expectations — Charles Dickens", genre: "Narrative Adventure", style: "8-bit", accent: "#c88820", status: "live",
    blurb: "Five acts from Dickens' 1861 classic — sneak provisions to Magwitch on the dark marshes, catch falling cake at Satis House, tap Jaggers' gavel in the golden zone, row Magwitch down the Thames, and face Compeyson in the icy river confrontation.", tags: ["drama","adventure","multi-chapter","dickens"] },
  { id: "heidi-alps", title: "Heidi", source: "Heidi — Johanna Spyri", genre: "Alpine Adventure", style: "8-bit", accent: "#f5c842", status: "live",
    blurb: "Five Alpine tales — dodge rocks up to Grandfather's alm, herd Peter's wandering goats, sneak past Miss Rottenmeier in Frankfurt, catch golden memories of home, and encourage Clara to take her first miraculous steps.", tags: ["adventure","cozy","multi-chapter"] },
  { id: "windwillows-toad", title: "The Wind in the Willows", source: "The Wind in the Willows — K. Grahame", genre: "Driving Arcade", style: "8-bit", accent: "#d8a020", status: "live",
    blurb: "Five tales from Grahame's riverside classic — steer Toad's motorcar, dodge weasels in the Wild Wood, pick the prison lock, catch Ratty's picnic treats on the river, and retake Toad Hall!", tags: ["driving","adventure","multi-chapter"] },
  { id: "ripvanwinkle-sleep", title: "Twenty Years Asleep", source: "Rip Van Winkle — Washington Irving", genre: "Puzzle Adventure", style: "8-bit", accent: "#F8B800", status: "live",
    blurb: "Five Catskill tales — hunt the mountains with Wolf, bowl with the ghostly hollow men, dream away twenty enchanted years, catch the memories of your old life, and prove to the changed village who you really are.", tags: ["puzzle","adventure","multi-chapter","folklore"] },
  { id: "piedpiper-tune", title: "The Pied Piper", source: "The Pied Piper of Hamelin", genre: "Rhythm Lead", style: "8-bit", accent: "#f0c030", status: "live",
    blurb: "Five tales of the Hamelin legend — drive off the rats, seal the Mayor's bargain, pipe the swarm to the river, survive his broken promise, and lead the children to the mountain with an enchanted tune.", tags: ["rhythm","music","multi-chapter"] },
  { id: "alibaba-cave", title: "Open Sesame", source: "Ali Baba and the Forty Thieves", genre: "Heist Puzzle", style: "8-bit", accent: "#d4a020", status: "live",
    blurb: "Five tales of gold and wit — hide from the forty thieves' lanterns, rush the treasure cave, mark every door to confuse the bandits, tap stirring oil jars before the captain signals, and time Morgiana's dagger-dance to unmask the last thief.", tags: ["puzzle","heist","multi-chapter","arabian"] },
  { id: "sinbad-voyage", title: "Sinbad the Sailor", source: "One Thousand and One Nights", genre: "Puzzle Adventure", style: "8-bit", accent: "#f0c030", status: "live",
    blurb: "Five voyages, five different games — rush crates off the sinking whale island, solve the Valley of Gems memory puzzle, sneak grapes past the sleeping Old Man, balance on the Roc's rope, and blast sea monsters with your cannons.", tags: ["adventure","puzzle","memory","stealth","multi-chapter","arabian"] },
  { id: "merlin-spells", title: "Merlin", source: "Merlin — Arthurian legend", genre: "Spell Puzzle", style: "8-bit", accent: "#b87aff", status: "live",
    blurb: "Five trials of the enchanter — catch wild runes in the ancient forest, survive the Red and White Dragons, soar as a falcon through arrow-filled skies, solve the living rune puzzle of the standing stones, and escape Nimue's closing crystal snare.", tags: ["puzzle","magic","multi-chapter","arthurian"] },
  { id: "scarletletter-a", title: "The Scarlet Letter", source: "The Scarlet Letter — N. Hawthorne", genre: "Narrative Stealth", style: "8-bit", accent: "#cc1122", status: "live",
    blurb: "Five Puritan chapters — deflect shame on the scaffold, redirect wild Pearl, parry Chillingworth's probing questions, navigate the dark forest to Dimmesdale, and hold his courage steady for the final confession.", tags: ["stealth","story","multi-chapter","puritan"] },
  { id: "princepauper-swap", title: "The Prince and the Pauper", source: "The Prince and the Pauper — Mark Twain", genre: "Swap Puzzle", style: "8-bit", accent: "#d4a820", status: "live",
    blurb: "Five Tudor tales from Twain's 1882 classic — sneak past the palace guards, survive a royal banquet, flee London's angry streets, parry Miles Hendon's enemies, and race to Westminster before the wrong boy is crowned.", tags: ["puzzle","adventure","multi-chapter"] },
  { id: "metamorphosis-bug", title: "The Metamorphosis", source: "The Metamorphosis — Franz Kafka", genre: "Survival Puzzle", style: "8-bit", accent: "#7a9c2a", status: "live",
    blurb: "Five scenes from Kafka's 1915 novella — dodge falling objects as Gregor wakes transformed, evade the panicking family, collect rotten food scraps, creep past scanning lodgers to hear the violin, and make the final slow crawl to peace before dawn.", tags: ["puzzle","survival","multi-chapter","kafka"] },
  { id: "asilaydying-journey", title: "As I Lay Dying", source: "As I Lay Dying — William Faulkner", genre: "Convoy Survival", style: "8-bit", accent: "#D4A020", status: "live",
    blurb: "Five chapters of the Bundren family's journey — steer a raft through the flooding river, haul the wagon through Mississippi dust, swat buzzards off the coffin, escape a burning barn, and navigate Jefferson to lay Addie to rest.", tags: ["survival","story","multi-chapter","faulkner"] },
  { id: "crusoe-island", title: "Robinson Crusoe", source: "Robinson Crusoe — Daniel Defoe (1719)", genre: "Island Survival", style: "8-bit", accent: "#d4b860", status: "live",
    blurb: "Five trials of the castaway — steer through the shipwreck storm, salvage supplies from the wreck, hide from cannibal scouts in the jungle, rescue Friday from the attackers, and signal a passing ship to earn your rescue after twenty-eight years.", tags: ["survival","adventure","multi-chapter"] },
  { id: "gulliver-travels", title: "Gulliver's Travels", source: "Gulliver's Travels — Jonathan Swift (1726)", genre: "Scale Adventure", style: "8-bit", accent: "#F8B800", status: "live",
    blurb: "Five voyages into several remote nations — survive the shipwreck storm, shoo the swarming Lilliputians, dodge giant boots in Brobdingnag, catch lodestones from the flying island of Laputa, and prove your reason to the noble Houyhnhnms.", tags: ["adventure","multi-chapter","satire"] },
  { id: "romeo-juliet", title: "Romeo & Juliet", source: "Romeo and Juliet — William Shakespeare (c.1594)", genre: "Romance Tragedy", style: "8-bit", accent: "#F878F8", status: "live",
    blurb: "Five scenes from Shakespeare's tragedy — crash the Capulet feast for roses, time the balcony climb to reach Juliet, duel Tybalt at noon, gather Friar Lawrence's sleeping herbs, and race through Verona past the watch to the Capulet tomb.", tags: ["romance","tragedy","multi-chapter","shakespeare"] },
  { id: "dante-inferno", title: "The Long Descent", source: "The Divine Comedy — Dante Alighieri (c.1320)", genre: "Dark Descent", style: "8-bit", accent: "#FC6000", status: "live",
    blurb: "Five circles from Dante's Inferno — dodge wild beasts in the dark wood, row Charon's ferry across the Acheron, survive the boiling blood of Phlegethon, sneak past Malebranche demons in Malebolge, and climb past Lucifer's frozen form to freedom.", tags: ["horror","descent","multi-chapter","classic"] },
  { id: "scarletpimpernel-rescue", title: "They Seek Him Here", source: "The Scarlet Pimpernel — Baroness Orczy (1905)", genre: "Stealth Swashbuckler", style: "8-bit", accent: "#D82800", status: "live",
    blurb: "Five escapades through revolutionary France — decode Sir Percy's coded dispatch, race the carriage to Calais past patrols, launch three guillotine diversions at the perfect moment, slip through the dark inn unseen, and duel Chauvelin on the Dover cliffs.", tags: ["stealth","swashbuckler","multi-chapter","historical"] },

  // ---------------------------- SOON (planned) ----------------------------
  { id: "hamlet-revenge", title: "The Prince of Denmark", source: "Hamlet — William Shakespeare (c.1600)", genre: "Revenge Thriller", style: "8-bit", accent: "#6828B4", status: "live",
    blurb: "Five acts of Shakespeare's greatest tragedy — dodge the Ghost on the battlements, expose Claudius with the Mousetrap, spy behind the arras, gather Ophelia's flowers, and duel Laertes on the fateful stage.", tags: ["shakespeare","tragedy","multi-chapter"] },
  { id: "blackbeauty-rider", title: "Black Beauty", source: "Black Beauty — Anna Sewell (1877)", genre: "Racing Adventure", style: "8-bit", accent: "#D8A000", status: "live",
    blurb: "Five rides through Beauty's life — gallop the open fields at Birtwick Park, endure the bearing rein, race to the doctor through the midnight storm, haul the London cab, and find the peaceful meadow of rest.", tags: ["racing","adventure","multi-chapter"] },
  { id: "swissfamily-island", title: "Swiss Family Robinson", source: "Swiss Family Robinson — Johann David Wyss (1812)", genre: "Island Survival", style: "8-bit", accent: "#00A800", status: "live",
    blurb: "Five island adventures — salvage the wreck, build the treehouse high in the great fig tree, hunt the jungle for provisions, defend against pirates, and finally choose who sails for home.", tags: ["survival","adventure","multi-chapter"] },
  { id: "ivanhoe-joust", title: "Ivanhoe", source: "Ivanhoe — Sir Walter Scott (1819)", genre: "Medieval Combat", style: "8-bit", accent: "#c8102e", status: "live",
    blurb: "Five knightly trials — time your lance at the Ashby joust, sneak through Torquilstone's torchlit corridors, parry and riposte against Brian de Bois-Guilbert, scale the castle wall through a storm of arrows, and fight at Richard's side to free Saxon England.", tags: ["joust","combat","multi-chapter","medieval"] },
];
