/* ============================================================================
 * POLECAT GAME CATALOG
 * ----------------------------------------------------------------------------
 * Single source of truth for every game on games.polecat.live.
 * The home page renders from this list; the hourly build-loop flips entries
 * from status:"soon" -> "live" as games ship, and may add screenshots/genres.
 *
 * Each entry:
 *   id      unique slug (also the folder under /games/<id>/)
 *   title   the game's name (not just the property)
 *   source  the public-domain property it draws from
 *   genre   gameplay category (drives variety + the genre filter)
 *   style   visual style ("8-bit" for now; future: "16-bit","vector","mono")
 *   accent  hex color used for the procedural thumbnail
 *   blurb   one-line pitch shown on the card
 *   status  "live" (playable) | "soon" (planned)
 *   tags    extra filter keywords
 * ============================================================================ */
window.POLECAT_CATALOG = [
  // ---------------------------- LIVE (built) ----------------------------
  { id: "sherlock-hound", title: "The Hound of the Baskervilles", source: "Sherlock Holmes — A. Conan Doyle", genre: "Mystery", style: "8-bit", accent: "#5dff8f", status: "live",
    blurb: "Five chapters of detection — deduce the cane, cross the Grimpen Mire, search the foggy moor, piece the warning, and face the Hound.", tags: ["detective","multi-chapter","mystery"] },
  { id: "dracula-castle", title: "Dracula", source: "Dracula — Bram Stoker", genre: "Horror", style: "8-bit", accent: "#c8102e", status: "live",
    blurb: "Five chapters through Stoker's novel — the castle wall, the doomed Demeter, Renfield's flies, Lucy's tomb, and the final reckoning at sunset.", tags: ["horror","multi-chapter","vampire"] },
  // ----------- LEGACY single-mechanic games (hidden from the home grid &
  // search via legacy:true until they're rebuilt in the multi-chapter story
  // mode). Still playable by direct URL; drop the flag once upgraded. -----------
  { id: "alice-rabbithole", title: "Alice in Wonderland", source: "Alice in Wonderland — Lewis Carroll", genre: "Story Arcade", style: "8-bit", accent: "#21e6ff", status: "live",
    blurb: "Five Wonderland tales — tumble down the rabbit hole, swim the pool of tears, time the Mad Hatter's cups, swing a flamingo at the Queen's croquet, and dodge flying cards at the trial!", tags: ["arcade","adventure","multi-chapter"] },
  { id: "oz-yellowbrick", title: "The Wizard of Oz", source: "The Wizard of Oz — L. Frank Baum", genre: "Story Arcade", style: "8-bit", accent: "#ffe14d", status: "live",
    blurb: "Five Oz tales — survive the twister, run the yellow brick road, wake friends in the poppy field, dodge the Wizard's fire, and click ruby heels to get home.", tags: ["arcade","adventure","multi-chapter"] },
  { id: "frankenstein-spark", title: "Frankenstein", source: "Frankenstein — Mary Shelley", genre: "Horror Adventure", style: "8-bit", accent: "#5dff8f", status: "live",
    blurb: "Five gothic chapters: channel lightning to birth the Creature, flee the frightened village, spy on the De Laceys, chase across Arctic ice, and make the final leap into darkness.", tags: ["horror","multi-chapter","gothic"] },

  // ---------------------------- SOON (planned) ----------------------------
  { id: "pooh-hunny", title: "Hunny Hunt", source: "Winnie-the-Pooh — A. A. Milne (1926)", genre: "Puzzle Collect", style: "8-bit", accent: "#ffe14d", status: "live",
    blurb: "Float by balloon to the bees' hive, follow the Woozle tracks, gather gifts for Eeyore's party, steer Piglet through the Blustery Day, and wiggle Pooh free from Rabbit's door.", tags: ["cozy","puzzle","multi-chapter"] },
  { id: "mickey-steamboat", title: "Steamboat Willie", source: "Mickey Mouse (1928 — Steamboat Willie)", genre: "Rhythm Action", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Pilot the riverboat and toot the whistle in time down the winding Mississippi.", tags: ["rhythm","classic"] },
  { id: "robinhood-archer", title: "Sherwood Sharpshooter", source: "Robin Hood — English folklore", genre: "Aim / Archery", style: "8-bit", accent: "#5dff8f", status: "live",
    blurb: "Split the shaft at the tournament, ride through Sherwood, duel Little John, rob the rich, and face the Sheriff to free Maid Marian.", tags: ["aim","skill","multi-chapter"] },
  { id: "arthur-sword", title: "The Sword in the Stone", source: "King Arthur — Arthurian legend", genre: "Action Adventure", style: "8-bit", accent: "#21e6ff", status: "live",
    blurb: "Pull Excalibur from the stone, joust at the tournament, defend Camelot's gates, and seek the Holy Grail across five chapters.", tags: ["adventure","quest","multi-chapter"] },
  { id: "peterpan-flight", title: "Second Star to the Right", source: "Peter Pan — J. M. Barrie", genre: "Flight Dodge", style: "8-bit", accent: "#ffe14d", status: "live",
    blurb: "Five Neverland tales — fly over London rooftops, rescue Tiger Lily, run from Tick-Tock the croc, defend the Lost Boys' hideout, and duel Captain Hook on the Jolly Roger.", tags: ["flight","dodge","multi-chapter"] },
  { id: "cinderella-ball", title: "Before Midnight", source: "Cinderella — Perrault / Grimm", genre: "Time Attack", style: "8-bit", accent: "#ff2e97", status: "live",
    blurb: "Finish the chores, catch the Fairy Godmother's sparkles, waltz with the Prince, race the midnight clock, and guide the glass slipper home.", tags: ["time","arcade","multi-chapter"] },
  { id: "snowwhite-apple", title: "Seven for the Mine", source: "Snow White — Brothers Grimm", genre: "Mining Puzzle", style: "8-bit", accent: "#5dff8f", status: "live",
    blurb: "Find Snow White in the magic mirror, flee the enchanted forest, catch gems in the dwarfs' mine, dodge the Evil Queen's poisoned apples, and fill the heart with true love's kiss.", tags: ["fairy-tale","puzzle","multi-chapter"] },
  { id: "tarzan-vines", title: "Lord of the Vines", source: "Tarzan of the Apes — E. R. Burroughs", genre: "Swing Platformer", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Time your grip and swing the jungle canopy at breakneck speed.", tags: ["swing","momentum"] },
  { id: "pinocchio-nose", title: "No Strings", source: "Pinocchio — Carlo Collodi", genre: "Platformer", style: "8-bit", accent: "#ffe14d", status: "soon",
    blurb: "Guide the puppet past Stromboli and the whale to become a real boy.", tags: ["platform","quest"] },
  { id: "hercules-labors", title: "The Twelve Labors", source: "Hercules — Greek mythology", genre: "Boss Rush", style: "8-bit", accent: "#ff8a3d", status: "soon",
    blurb: "Battle the Nemean Lion, Hydra, and more in twelve legendary trials.", tags: ["boss","action"] },
  { id: "thor-loki", title: "Hammer of the Gods", source: "Thor & Loki — Norse mythology", genre: "Brawler", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Hurl Mjölnir across the Nine Realms and outsmart Loki's trickery.", tags: ["brawler","action"] },
  { id: "pride-prejudice", title: "A Matter of Pride", source: "Pride and Prejudice — Jane Austen", genre: "Dialogue Strategy", style: "8-bit", accent: "#ff2e97", status: "soon",
    blurb: "Navigate the ballroom of wit — match words to win hearts and avoid scandal.", tags: ["social","puzzle"] },
  { id: "gatsby-green", title: "The Green Light", source: "The Great Gatsby — F. Scott Fitzgerald", genre: "Rhythm Party", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Throw the jazziest party on West Egg and reach across the bay for the light.", tags: ["rhythm","style"] },
  { id: "scrooge-carol", title: "Scrooge's Long Night", source: "A Christmas Carol — Charles Dickens", genre: "Narrative Maze", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Walk past, present, and yet-to-come to thaw a frozen heart by dawn.", tags: ["story","maze"] },
  { id: "musketeers-duel", title: "All for One", source: "The Three Musketeers — Alexandre Dumas", genre: "Fencing Duel", style: "8-bit", accent: "#ff8a3d", status: "soon",
    blurb: "Parry, riposte, and duel the Cardinal's guards across Paris rooftops.", tags: ["duel","action"] },
  { id: "montecristo-escape", title: "The Count's Revenge", source: "The Count of Monte Cristo — Dumas", genre: "Stealth Escape", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Tunnel out of the Château d'If, then plot your patient, perfect revenge.", tags: ["stealth","puzzle"] },
  { id: "mobydick-hunt", title: "The White Whale", source: "Moby-Dick — Herman Melville", genre: "Harpoon Action", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Steady the Pequod and harpoon the leviathan before obsession sinks you.", tags: ["action","sea"] },
  { id: "phantom-opera", title: "Beneath the Opera", source: "The Phantom of the Opera — G. Leroux", genre: "Stealth Pursuit", style: "8-bit", accent: "#ff2e97", status: "soon",
    blurb: "Haunt the catacombs below the Palais Garnier and claim the chandelier.", tags: ["stealth","horror"] },
  { id: "phantom-1925", title: "The Masque", source: "Phantom of the Opera (1925 film)", genre: "Chase", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Unmask and flee through the silent-film shadows of the opera house.", tags: ["chase","horror"] },
  { id: "zorro-mark", title: "The Mark of Zorro", source: "Zorro — The Curse of Capistrano", genre: "Swashbuckler", style: "8-bit", accent: "#ff2e97", status: "soon",
    blurb: "Carve your Z, rescue the people, and vanish before the Alcalde's men.", tags: ["action","duel"] },
  { id: "timemachine-eloi", title: "802,701 A.D.", source: "The Time Machine — H. G. Wells", genre: "Survival Strategy", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Leap across eras to retrieve your machine from the Morlocks below.", tags: ["survival","scifi"] },
  { id: "warworlds-tripods", title: "Tripods", source: "The War of the Worlds — H. G. Wells", genre: "Survival Shooter", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Outlast the Martian heat-rays across a burning English countryside.", tags: ["shooter","survival"] },
  { id: "jekyll-hyde", title: "Two Minds", source: "Dr. Jekyll and Mr. Hyde — R. L. Stevenson", genre: "Transformation Puzzle", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Flip between gentle Jekyll and monstrous Hyde to solve each foggy street.", tags: ["puzzle","horror"] },
  { id: "nemo-nautilus", title: "20,000 Leagues", source: "Captain Nemo — Jules Verne", genre: "Submarine Shmup", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Dive the Nautilus through trenches, giant squid, and sunken ruins.", tags: ["shmup","sea"] },
  { id: "cthulhu-call", title: "The Call", source: "The Call of Cthulhu — H. P. Lovecraft", genre: "Sanity Survival", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Chart the nightmare seas to R'lyeh while your sanity slips away.", tags: ["horror","survival"] },
  { id: "kingkong-climb", title: "Eighth Wonder", source: "King Kong (1932 novelization)", genre: "Climb Defense", style: "8-bit", accent: "#ff8a3d", status: "soon",
    blurb: "Scale the skyscraper as Kong and swat the biplanes from the sky.", tags: ["climb","action"] },
  { id: "notld-survive", title: "They're Coming", source: "Night of the Living Dead (1968)", genre: "Tower Defense", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Board the windows and survive the night against the relentless dead.", tags: ["defense","horror"] },
  { id: "littlemermaid-sea", title: "The Sea King's Daughter", source: "The Little Mermaid — H. C. Andersen", genre: "Swim Collect", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Swim the deep, trade with the sea witch, and rise toward the surface world.", tags: ["swim","story"] },
  { id: "tomsawyer-fence", title: "Whitewash", source: "Tom Sawyer — Mark Twain", genre: "Painting Arcade", style: "8-bit", accent: "#ffe14d", status: "soon",
    blurb: "Trick the whole town into painting Aunt Polly's fence — for a price.", tags: ["arcade","fun"] },
  { id: "huckfinn-raft", title: "Down the Mississippi", source: "Huckleberry Finn — Mark Twain", genre: "River Runner", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Steer the raft past steamboats and snags on the long road to freedom.", tags: ["runner","river"] },
  { id: "lesmis-escape", title: "24601", source: "Les Misérables — Victor Hugo", genre: "Stealth", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Slip through the Paris barricades a step ahead of Inspector Javert.", tags: ["stealth","story"] },
  { id: "doriangray-portrait", title: "The Portrait", source: "The Picture of Dorian Gray — O. Wilde", genre: "Decay Puzzle", style: "8-bit", accent: "#ff2e97", status: "soon",
    blurb: "Keep your face flawless as the hidden portrait rots with every sin.", tags: ["puzzle","horror"] },
  { id: "grimm-tales", title: "Grimm's Path", source: "Grimm's Fairy Tales", genre: "Story Roguelite", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Wander a dark forest of tales where each path tells a different Grimm story.", tags: ["roguelite","story"] },
  { id: "1001nights-magic", title: "A Thousand Nights", source: "One Thousand and One Nights", genre: "Adventure", style: "8-bit", accent: "#ff8a3d", status: "soon",
    blurb: "Spin Scheherazade's tales across deserts, genies, and flying carpets.", tags: ["adventure","magic"] },
  { id: "odysseus-voyage", title: "The Long Way Home", source: "Odysseus — The Odyssey", genre: "Voyage Adventure", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Sail past Cyclops, Sirens, and Scylla on the ten-year road to Ithaca.", tags: ["adventure","sea"] },
  { id: "odyssey-sirens", title: "Song of the Sirens", source: "The Odyssey — Homer", genre: "Rhythm Dodge", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Lash to the mast and resist the Sirens' hypnotic, deadly song.", tags: ["rhythm","myth"] },
  { id: "iliad-troy", title: "Wrath of Achilles", source: "The Iliad — Homer", genre: "Battle Tactics", style: "8-bit", accent: "#ff8a3d", status: "soon",
    blurb: "Lead the Greeks across the plains of Troy and storm the walls.", tags: ["tactics","war"] },
  { id: "beowulf-grendel", title: "Beowulf", source: "Beowulf — Old English epic", genre: "Boss Brawler", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Tear into Grendel in the mead-hall, then dive to face his vengeful mother.", tags: ["boss","brawler"] },
  { id: "hunchback-bells", title: "The Bells of Notre-Dame", source: "The Hunchback of Notre-Dame — Hugo", genre: "Climb Rescue", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Swing the great bells and scale the cathedral to claim sanctuary.", tags: ["climb","story"] },
  { id: "nosferatu-1922", title: "Shadow of the Vampyr", source: "Nosferatu (1922 film)", genre: "Stealth Horror", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Keep Count Orlok in shadow and survive until the cock crows at dawn.", tags: ["horror","stealth"] },
  { id: "metropolis-1927", title: "Heart Machine", source: "Metropolis (1927 film)", genre: "Industrial Platformer", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Descend to the workers' city and keep the great machine from exploding.", tags: ["platform","scifi"] },
  { id: "mulan-ballad", title: "Ballad of Mulan", source: "Hua Mulan — Ballad of Mulan", genre: "Action RPG", style: "8-bit", accent: "#ff2e97", status: "soon",
    blurb: "Train in secret, ride to war, and bring honor home in your father's stead.", tags: ["rpg","action"] },
  { id: "scrooge-ledger", title: "Bah, Humbug!", source: "Ebenezer Scrooge — A Christmas Carol", genre: "Idle Tycoon", style: "8-bit", accent: "#ffe14d", status: "soon",
    blurb: "Count the coins by candlelight — but generosity may pay the richest dividend.", tags: ["idle","management"] },
  { id: "tripmoon-1902", title: "A Trip to the Moon", source: "A Trip to the Moon (1902 film)", genre: "Cannon Launch", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Fire the great cannon, land in the Moon's eye, and flee the Selenites.", tags: ["launch","arcade"] },
  { id: "sleepyhollow-ride", title: "The Headless Horseman", source: "The Legend of Sleepy Hollow — Irving", genre: "Night Chase", style: "8-bit", accent: "#ff8a3d", status: "soon",
    blurb: "Race Ichabod through the haunted wood and reach the covered bridge.", tags: ["chase","horror"] },
  { id: "invisibleman-fade", title: "Unseen", source: "The Invisible Man — H. G. Wells", genre: "Stealth Puzzle", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Use your invisibility to slip past the mob — but rain and snow give you away.", tags: ["stealth","puzzle"] },
  { id: "journeycenter-earth", title: "To the Center", source: "Journey to the Center of the Earth — Verne", genre: "Descent Platformer", style: "8-bit", accent: "#ff8a3d", status: "soon",
    blurb: "Spelunk past prehistoric beasts and a subterranean sea to the Earth's core.", tags: ["platform","explore"] },
  { id: "around80days-race", title: "Around the World", source: "Around the World in Eighty Days — Verne", genre: "Race Manager", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Plot trains, ships, and elephants to circle the globe and win the wager.", tags: ["race","strategy"] },
  { id: "treasureisland-map", title: "X Marks the Spot", source: "Treasure Island — R. L. Stevenson", genre: "Treasure Hunt", style: "8-bit", accent: "#ffe14d", status: "live",
    blurb: "Find the map at the inn, sail the Hispaniola through treacherous seas, hold the stockade, slip through the jungle, and dig for Flint's buried hoard.", tags: ["adventure","pirate","multi-chapter"] },
  { id: "junglebook-mowgli", title: "The Jungle Book", source: "The Jungle Book — Rudyard Kipling", genre: "Stealth Platformer", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Run with the wolf pack and slip past Shere Khan through the deep jungle.", tags: ["platform","stealth"] },
  { id: "donquixote-tilt", title: "Tilting at Windmills", source: "Don Quixote — Cervantes", genre: "Joust Arcade", style: "8-bit", accent: "#ff8a3d", status: "soon",
    blurb: "Charge the 'giants' on Rocinante in the most gallant, hopeless quest of all.", tags: ["arcade","comedy"] },
  { id: "annegreen-gables", title: "Anne of Green Gables", source: "Anne of Green Gables — Montgomery", genre: "Life Sim", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Tend Green Gables through the seasons and grow Avonlea's biggest imagination.", tags: ["cozy","sim"] },
  { id: "littlewomen-march", title: "Little Women", source: "Little Women — Louisa May Alcott", genre: "Story Sim", style: "8-bit", accent: "#ff2e97", status: "soon",
    blurb: "Guide the four March sisters through a year of trials, plays, and growing up.", tags: ["story","sim"] },
  { id: "secretgarden-bloom", title: "The Secret Garden", source: "The Secret Garden — F. H. Burnett", genre: "Garden Puzzle", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Find the hidden key and coax a dead garden — and a lonely house — back to life.", tags: ["puzzle","cozy"] },
  { id: "whitefang-wild", title: "White Fang", source: "White Fang — Jack London", genre: "Survival Sim", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Survive the frozen Yukon as a wolf-dog torn between the wild and the fire.", tags: ["survival","animal"] },
  { id: "callwild-buck", title: "The Call of the Wild", source: "The Call of the Wild — Jack London", genre: "Sled Runner", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Pull the sled through blizzards as Buck and answer the howl of the wild.", tags: ["runner","animal"] },
  { id: "olivertwist-dodge", title: "Please, Sir", source: "Oliver Twist — Charles Dickens", genre: "Pickpocket Stealth", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Learn the Dodger's trade in the London streets without landing in the clink.", tags: ["stealth","arcade"] },
  { id: "greatexpect-pip", title: "Great Expectations", source: "Great Expectations — Charles Dickens", genre: "Narrative Adventure", style: "8-bit", accent: "#ffe14d", status: "soon",
    blurb: "Rise from the marsh forge to London society — and learn who your benefactor is.", tags: ["story","adventure"] },
  { id: "heidi-alps", title: "Heidi", source: "Heidi — Johanna Spyri", genre: "Mountain Platformer", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Herd goats across the sunny Alps and bring cheer to the lonely Alm-Uncle.", tags: ["platform","cozy"] },
  { id: "windwillows-toad", title: "The Wind in the Willows", source: "The Wind in the Willows — K. Grahame", genre: "Driving Arcade", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Poop-poop! Tear down country lanes as Mr. Toad and retake Toad Hall.", tags: ["driving","comedy"] },
  { id: "ripvanwinkle-sleep", title: "Twenty Years Asleep", source: "Rip Van Winkle — Washington Irving", genre: "Puzzle Adventure", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Wake from a twenty-year nap and piece together a village that left you behind.", tags: ["puzzle","story"] },
  { id: "piedpiper-tune", title: "The Pied Piper", source: "The Pied Piper of Hamelin", genre: "Rhythm Lead", style: "8-bit", accent: "#ff8a3d", status: "soon",
    blurb: "Pipe a hypnotic tune and lead the rats — then the children — out of Hamelin.", tags: ["rhythm","music"] },
  { id: "alibaba-cave", title: "Open Sesame", source: "Ali Baba and the Forty Thieves", genre: "Heist Puzzle", style: "8-bit", accent: "#ffe14d", status: "soon",
    blurb: "Speak the words, grab the treasure, and escape the thieves' cave in time.", tags: ["puzzle","heist"] },
  { id: "sinbad-voyage", title: "Sinbad the Sailor", source: "Sinbad the Sailor", genre: "Voyage Shmup", style: "8-bit", accent: "#21e6ff", status: "soon",
    blurb: "Sail seven voyages past the Roc, the whale-island, and the Old Man of the Sea.", tags: ["shmup","adventure"] },
  { id: "merlin-spells", title: "Merlin", source: "Merlin — Arthurian legend", genre: "Spell Puzzle", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Weave runes into spells to guide young Arthur and shape Britain's fate.", tags: ["puzzle","magic"] },
  { id: "scarletletter-a", title: "The Scarlet Letter", source: "The Scarlet Letter — N. Hawthorne", genre: "Narrative Stealth", style: "8-bit", accent: "#ff2e97", status: "soon",
    blurb: "Walk Puritan Boston under judging eyes and guard a dangerous secret.", tags: ["story","stealth"] },
  { id: "princepauper-swap", title: "The Prince and the Pauper", source: "The Prince and the Pauper — Twain", genre: "Swap Puzzle", style: "8-bit", accent: "#ffe14d", status: "soon",
    blurb: "Switch between palace and gutter to fix two lives that got swapped by mistake.", tags: ["puzzle","story"] },
  { id: "metamorphosis-bug", title: "Metamorphosis", source: "The Metamorphosis — Franz Kafka", genre: "Crawl Puzzle", style: "8-bit", accent: "#5dff8f", status: "soon",
    blurb: "Wake as a giant insect and navigate a home that no longer wants you.", tags: ["puzzle","surreal"] },
  { id: "asilaydying-journey", title: "As I Lay Dying", source: "As I Lay Dying — William Faulkner", genre: "Convoy Survival", style: "8-bit", accent: "#9b5cff", status: "soon",
    blurb: "Haul the family coffin across flood and fire to the burial ground in Jefferson.", tags: ["survival","story"] },
];
